version: "3"
services:
  django-app:
    build:
      context: ./Django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  # other-service:
  #   # Add configuration for your other service(s) here
